import React, { useState } from "react";
import ExpenseDate from "./ExpenseDate";
import Card from "../UI/Card";
import "./ExpenseItem.css";

const ExpenseItem = (props) => {
  const [title, setTitle] = useState(props.title);


  const clickHandler = () => {
    setTitle('Updated');
  };

  return (
    <Card className="expense-item">
      <ExpenseDate date={props.date} />
      <div className="expense-item__description">
        <h2>{title}</h2>
        <div className="expense-item__price">${props.amount}</div>
      </div>

      <button onClick={clickHandler}>Change title</button>
    </Card>
  );
};

export default ExpenseItem;



// COMPONENTS ARE JUST FUNCTIONS,THE DIFFERENCE ONLY THAT THEY ARE RETURN JSX
// 1.WE CAN DEFINE ANY JS VARIAB AND OUTPUT DYNAMIC DATA WITH JSX SNIPPETS {}
// 2.BUT WE WILL OUTPUT IT VIA PROPS
// WE NEED TO OUTPUT DATA FROM OUTSIDE (FROM SOME OBJECT), NOT FROM COMPONENT
// WE DEFINE DATA IN APP COMPONENT AS AN OBJECT (FOR DIFFERENT DATA)

// 3.THEN WE INSERT DATA BY ATTRIBUTES IN COMPONENT (JUST PASS IT)
// THEN WE NEED TO ACCESS THIS INSERTED DATA TO DISPLAY IT, LIKE PROPS.TITLE
// (PARAMETER PROPS IT'S A NEW OBJECT WITH INSERTED DATA; ATTR ARE THE KEYS OF THIS OBJECT)
// (WE PASS DATA FROM A COMPONENT TO A DIRECT CHILD OF COMPONENT, AND WE CAN'T SKIP ANOTHER EL)

// 4.ALSO WE CAN ADD AN EVENT LISTENER TO THE EL (we just point to the function, not execute it)
// BETTER TO CALL SUCH FUNCTIONS AS SMTH HANDLER

// 5.STATE CONCEPT
// WE CAN'T CHANGE TITLE ON CLICK BY CHANGING IT IN FUNCTION
// BECAUSE AFTER INITIAL RENDERING EXPENSEITEM FUNCTION DOES'T CALLED SECOND TIME
// FOR MAKING THAT, 
// 1. WE NEED TO IMPORT USE STATE FUNCTION FROM REACT LIBRARY
// 2. WE REGISTER STATE (PROPS.TITLE) WITH USESTATE FUNCTION INSIDE A COMPONENT - IT'S A REACT HOOK
// 3. FIRST ELEMENT IS A VALUE ITSELF (POINTER TO PROPS.TITLE IN USESTATE) - CURRENT STATE VALUE
// 4. THE SECOND ELEMENT IS AN UPDATING FUNCTION
// 5. AND THEN WE CALL THIS FUNCTION WITH DESIRED VALUE INSIDE, WHERE WE NEED IT
// -SO IT WILL CALL COMPONENT FUNCTION AGAIN AND CHANGE THE VALUE
// -IT IS AFFECTED ON ONE SPECIFIC COMPONENT INSTANCE (OF 4 HERE) 
// -WE USE THE FIRST VALUE IN JSX (TITLE), BECAUSE WHEN COMPONENT FUNCTION IS BEING EXECUTED FIRST TIME,
// THE INITIAL VALUE IN USE STATE (PROPS.TITLE) IS ONLY CONSIDERED
// SO WE DON'T NEED TO DEFINE IT
