// WE CAN USE COMPONENTS AS CONTAINERS WITH COMMON STYLES
// THEN WE CAN WRAP SOME EL WITH THIS
// BUT WE NEED TO PUT PROPS.CHILDREN SO IT WILL WORKS ON THE INNER CONTENT OF THIS EL

import './Card.css';

// HERE TO MAKE CLASSES WORK ON ELEMENT (LIKE EXPENSE-ITEM CLASS)
// WE NEED TO TELL OUR COMPONENT THAT IT HAVE TO APPLY CLASSES (PROPS.CLASSNAME FOR ANY WHICH WE WILL SET)
// WE CAN SET HERE CARD AS A DEFAULT CLASS WHICH IS ALWAYS APPLIED

const Card = (props) => {
    const classes = 'card ' + props.className;

    return <div className={classes}>{props.children}</div>
}

export default Card;